//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCdatabasefirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDetails
    {
        public int EmpID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public string Worktype { get; set; }
    }
}
